# WIP: This still won't run successfully and hangs with: 
# [java] Waiting for http://localhost:3636 (#<Errno::ECONNREFUSED: Connection refused - Failed to open TCP connection to localhost:3636 (Connection refused - connect(2) for "localhost" port 3636)>)
# [java] ERROR: Edit mediator: connection refused: localhost:3636: ["/home/runner/work/caas_aspace_sova_button/caas_aspace_sova_button/build/gems/jruby/2.5.0/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:890:in `reset'", "/home/runner/work/caas_aspace_sova_button/caas_aspace_sova_button/build/gems/jruby/2.5.0/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:567:in `connection_for'", "/home/runner/work/caas_aspace_sova_button/caas_aspace_sova_button/build/gems/jruby/2.5.0/gems/net-http-persistent-2.8/lib/net/http/persistent.rb:926:in `request'", "uri:classloader:/jsonmodel_client.rb:234:in `do_http_request'", "uri:classloader:/jsonmodel_client.rb:143:in `post_form'", "/home/runner/work/caas_aspace_sova_button/caas_aspace_sova_button/frontend/app/models/edit_mediator.rb:68:in `log_in_to_backend'", "/home/runner/work/caas_aspace_sova_button/caas_aspace_sova_button/frontend/app/models/edit_mediator.rb:97:in `synchronise_with_backend'", "/home/runner/work/caas_aspace_sova_button/caas_aspace_sova_button/frontend/app/models/edit_mediator.rb:117:in `block in start'"]
name: Frontend Plugin Testing

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  frontend_plugins:
    runs-on: ubuntu-latest
    env:
      PROD_ARCHIVESSPACE_VERSION: v3.5.1

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: archivesspace
          MYSQL_USER: as
          MYSQL_PASSWORD: as123
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      solr:
        image: archivesspace/solr:latest
        ports:
          - 8984:8983

    steps:
    - name: Checkout ArchivesSpace
      uses: actions/checkout@v4
      with:
        ref: ${{ env.PROD_ARCHIVESSPACE_VERSION }}
        repository: Smithsonian/archivesspace

    - name: Checkout plugin
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Copy plugin to ArchivesSpace and add to config
      run: |
        cp -r ${{ github.workspace }}/${{ github.event.repository.name }} ${{ github.workspace }}/plugins
        cd ./common/config/
        touch config.rb
        echo "AppConfig[:plugins] = ['${{ github.event.repository.name }}']" > config.rb

    - uses: Smithsonian/caas-aspace-services/.github/actions/bootstrap@main
      with:
        backend: true
        frontend: true
        indexer: true

    - name: Allow ArchivesSpace functions for app db user
      env:
        DB_PORT: "3307"
      run: |
        mysql --host 127.0.0.1 --port $DB_PORT -uroot -proot -e "SET GLOBAL log_bin_trust_function_creators = 1;"
  
    - name: Create ArchivesSpace Solr core
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker exec --tty $SOLR_ID solr create_core -p 8983 -c archivesspace -d /archivesspace

    - name: Run Backend plugin tests
      run: |
        ./build/run frontend:test -Dpattern="../../plugins/${{ github.event.repository.name }}/frontend/spec/*"
