name: Frontend Plugin Testing

on: 
  pull_request:
    branches:
      - main
  push:

jobs:
  frontend_plugins:
    runs-on: ubuntu-latest
    env:
      PROD_ARCHIVESSPACE_VERSION: v3.3.1
      PROD_JAVA_VERSION: '11'

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: archivesspace
          MYSQL_USER: as
          MYSQL_PASSWORD: as123
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      solr:
        image: archivesspace/solr:latest
        ports:
          - 8984:8983

    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.PROD_JAVA_VERSION }}

    - name: Allow ArchivesSpace functions for app db user
      env:
        DB_PORT: "3307"
      run: |
        mysql --host 127.0.0.1 --port $DB_PORT -uroot -proot -e "SET GLOBAL log_bin_trust_function_creators = 1;"
  
    - name: Create ArchivesSpace Solr core
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker exec --tty $SOLR_ID solr create_core -p 8983 -c archivesspace -d /archivesspace
        
    - name: Checkout ArchivesSpace
      uses: actions/checkout@v4
      with:
        ref: v3.3.1-for-test
        repository: lorawoodford/archivesspace

    - name: Checkout plugin
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Copy plugin to ArchivesSpace
      run: |
        cp -r ${{ github.workspace }}/${{ github.event.repository.name }} ${{ github.workspace }}/plugins

    - name: Add plugin to config
      run: |
        cd ./common/config/
        touch config.rb
        echo "AppConfig[:plugins] = ['${{ github.event.repository.name }}']" > config.rb
    
    - name: Bootstrap ArchivesSpace
      run: |
        ./build/run bootstrap
        wget -P ./common/lib https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar

    - name: Run Frontend plugin tests
      run: |
        ./build/run frontend:selenium -Dspec="../../plugins/${{ github.event.repository.name }}"
